name: 'actions-android-ci'
description: 'Run Android build with GitHub Actions'
author: 'xdtianyu'
icon: 'package'
color: 'green'
inputs: 
  build:
    description: 'Build android app with gradle'
    default: '"
        source .travis/env.sh;
        touch local.properties;
        source /opt/setup-android-sdk.sh;
        ./gradlew assembleDebug
        "'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.build }}
